require "lew.keymaps"
require "lew.plugins"
require "lew.autocommands"
require "lew.colorscheme"
require "lew.cmp"
require "lew.navic"
require "lew.lsp"
-- require "lew.lsp-inlayhints"
require "lew.telescope"
require "lew.treesitter"
require "lew.colorizer"
-- require "lew.colortils"
require "lew.autopairs"
require "lew.rest-nvim"
require "lew.nvim-comment"
require "lew.lualine"
require "lew.nvimtree"
-- require "lew.jabs"
require "lew.blankline"
require "lew.fidget"
require "lew.project"
require "lew.jaq"
require "lew.lab"
require "lew.alpha"
require "lew.trouble"
require "lew.toggleterm"
require "lew.gitsigns"
-- require "lew.gps"
require "lew.neoscroll"
require "lew.illuminate"
require "lew.comment"
-- require "lew.quickscope"
require "lew.todo-comments"
require "lew.vim-slash"
require "lew.symbol-outline"
require "lew.numb"
require "lew.dressing"
require "lew.notify"
require "lew.hop"
require "lew.dap"
require "lew.winbar"
require "lew.crates"
require "lew.cybu"
require "lew.bfs"
require "lew.functions"
require "lew.webdev-icons"
require "lew.options"
