require("lew.plugins")
require("lew.keymaps")
require("lew.settings")
require("lew.colorscheme")
-- require("lew.colorizer")
require("lew.nvim-comment")
require("lew.lsp")
require("lew.cmp")
require("lew.autocommands")
require("lew.telescope")
require("lew.lualine")
require("lew.bufferline")
require("lew.nvimtree")
require("lew.treesitter")
require("lew.blankline")
-- require("lew.dashboard")
require("lew.project")
require("lew.alpha")
-- require("lew.surround")
require("lew.autopairs")
require("lew.autotag")
require("lew.trouble")
require("lew.toggleterm")
require("lew.gitsigns")
-- require("lew.gps")
require("lew.neoscroll")
require("lew.illuminate")
require("lew.comment")
require("lew.quickscope")
require("lew.jabs")
require("lew.todo-comments")
require("lew.symbol-outline")
require("lew.renamer")
-- require("lew.lir")
